### ISSUE TITLE
Rospy service Exception : Transport error completing service call

### ISSUE THREAD

**Issue by dhananjayrajmane** [qiayuanl/legged_control#60]
While running legged control, I am getting following exception : 

#### 'pawup.modeSequence': {RF_LH_RH} 
[ INFO] [1708660110.135367770]: legged_robot_mpc_mode_schedule command node is ready.
Enter the desired gait, for the list of available gait enter "list": Loaded 'controllers/joint_state_controller'
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    responses = transport.receive_once()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 744, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 111, in recv_buff
    raise TransportTerminated("unable to receive data from sender, check sender's logs for details")
rospy.exceptions.TransportTerminated: unable to receive data from sender, check sender's logs for details

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/controller_manager/controller_manager", line 49, in <module>
    controller_manager_interface.load_controller(c)
  File "/opt/ros/noetic/lib/python3/dist-packages/controller_manager/controller_manager_interface.py", line 61, in load_controller
    resp = s.call(LoadControllerRequest(name))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 533, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

**Comment by Libre007** [comment]
Hello, have you resolved the issue? I've encountered the same problem as well.
